Update Kwaizeer.md
iris-hep/iris-hep.github.io pull request #2243
Opened 2024-06-16 17:34 UTC by Kwaizer

2024-06-16 17:41 UTC, Kwaizer commented
@matthewfeickert please review when you'll be available

2024-06-17 22:49 UTC, matthewfeickert requested changes
@Kwaizer Looks pretty good, but I think we can improve the project description a bit. :+1:

2024-06-17 22:49 UTC, matthewfeickert commented on pages/fellows/2023/Kwaizer.md
> +    After packaging of needed components will be finished it will allow them to have the ability to not only be installed as individual tools, but also be installed together in a coherent package env
```suggestion
    To package components of the HEP simulation software stack on conda-forge in an interoperable manner, making them easier to quickly and correctly install in a software environment, and use together.
```

2024-06-18 16:14 UTC, matthewfeickert approved these changes

2024-06-18 16:17 UTC, merged